CREATE TABLE tbTrangThaiHopDongVay (
	MaTrangThai CHAR(36) NOT NULL,
	TenTrangThai NVARCHAR(128) NOT NULL,
	MucRuiRo TINYINT NOT NULL,
	PRIMARY KEY (MaTrangThai)
)

CREATE TABLE tbTrangThaiTaiSan (
	MaTrangThai CHAR(36) NOT NULL,
	TenTrangThai NVARCHAR(128) NOT NULL,
	MucDanhGia DECIMAL(15,13) NOT NULL
	PRIMARY KEY (MaTrangThai)
)

CREATE TABLE tbDinhDanh (
	MaDinhDanh CHAR(36) NOT NULL,
	LoaiDinhDanh TINYINT NOT NULL,
	GiaTri VARCHAR(64) NOT NULL
	PRIMARY KEY (MaDinhDanh)
)

CREATE TABLE tbThamSoKyHanLaiSuat (
	KyHan INT NOT NULL,
	LaiSuat DECIMAL(7, 3) NOT NULL
	PRIMARY KEY (KyHan)
)

CREATE TABLE tbDieuKhoan (
	MaDieuKhoan CHAR(36) NOT NULL,
	MoTa NVARCHAR(512) NOT NULL
	PRIMARY KEY (MaDieuKhoan)
)

CREATE TABLE tbChiTietDoanhNghiep (
	MaDoanhNghiep CHAR(36),
	MaDangKy VARCHAR(64),
	TenDoanhNghiep NVARCHAR(256),
	LinhVuc NVARCHAR(128),
	ChucVuDaiDien NVARCHAR(64),
	PRIMARY KEY (MaDoanhNghiep)
)

CREATE TABLE tbKhachHang (
	MaKH CHAR(36) NOT NULL,
	HoTen NVARCHAR(128) NOT NULL,
	NgaySinh DATE NOT NULL,
	SDT NVARCHAR(25) NOT NULL,
	DiaChi NVARCHAR(256) NOT NULL,
	MaDinhDanh CHAR(36) NOT NULL,
	MaDoanhNghiepDaiDien CHAR(36),
	GioiTinh VARCHAR(10) NOT NULL
	PRIMARY KEY (MaKH)
	FOREIGN KEY (MaDinhDanh) REFERENCES tbDinhDanh(MaDinhDanh),
	FOREIGN KEY (MaDoanhNghiepDaiDien) REFERENCES tbChiTietDoanhNghiep(MaDoanhNghiep)
)

CREATE TABLE tbGiaoDich (
	MaGiaoDich CHAR(36) NOT NULL,
	LoaiGiaoDich TINYINT NOT NULL,
	DonViGiaoDich CHAR(36),
	GiaTri DECIMAL(32, 2) NOT NULL,
	ThoiDiemThucHien DATETIME NOT NULL,
	MoTa NVARCHAR(512) NOT NULL
	FOREIGN KEY (DonViGiaoDich) REFERENCES tbKhachHang(MaKH)
	PRIMARY KEY (MaGiaoDich)
)

CREATE TABLE tbNhanVien (
	MaNV CHAR(36) NOT NULL,
	HoTen NVARCHAR(128) NOT NULL,
	TenDangNhap VARCHAR(64) NOT NULL,
	MatKhau VARCHAR(64) NOT NULL,
	NgaySinh DATE NOT NULL,
	SDT VARCHAR(25) NOT NULL,
	DiaChi NVARCHAR(256) NOT NULL,
	NgayVaoLam DATE NOT NULL,
	MaDinhDanh CHAR(36) NOT NULL,
	LoaiNhanVien TINYINT NOT NULL
	PRIMARY KEY (MaNV)
	FOREIGN KEY (MaDinhDanh) REFERENCES tbDinhDanh(MaDinhDanh)
)

CREATE TABLE tbKQXetDuyet (
	MaKQXetDuyet CHAR(36) NOT NULL,
	MaNVXetDuyet CHAR(36) NOT NULL,
	coChapNhan BIT NOT NULL,
	LyDo NVARCHAR(512)
	PRIMARY KEY (MaKQXetDuyet)
	FOREIGN KEY (MaNVXetDuyet) REFERENCES tbNhanVien(MaNV)
)

CREATE TABLE tbYeuCauChoVay (
	MaYeuCau CHAR(36) NOT NULL,
	MaKHYeuCau CHAR(36) NOT NULL,
	MaNVTiepNhan CHAR(36) NOT NULL,
	SoTienVay DECIMAL(32, 2) NOT NULL,
	LaiSuat DECIMAL(7, 3) NOT NULL,
	KiHan INT NOT NULL,
	MaKQXetDuyet CHAR(36),
	ThoiDiemTiepNhan DATETIME
	PRIMARY KEY (MaYeuCau)
	FOREIGN KEY (MaKHYeuCau) REFERENCES tbKhachHang(MaKH),
	FOREIGN KEY (MaNVTiepNhan) REFERENCES tbNhanVien(MaNV),
	FOREIGN KEY (MaKQXetDuyet) REFERENCES tbKQXetDuyet(MaKQXetDuyet)
)

CREATE TABLE tbDieuKhoanHopDong (
	MaYeuCau CHAR(36) NOT NULL,
	MaDieuKhoan CHAR(36) NOT NULL
	PRIMARY KEY (MaYeuCau, MaDieuKhoan)
	FOREIGN KEY (MaYeuCau) REFERENCES tbYeuCauChoVay(MaYeuCau),
	FOREIGN KEY (MaDieuKhoan) REFERENCES tbDieuKhoan(MaDieuKhoan)
)

CREATE TABLE tbHopDongVay (
	MaHopDong CHAR(36) NOT NULL,
	MaYeuCau CHAR(36) NOT NULL,
	MaNVTiepNhan CHAR(36) NOT NULL,
	NgayThietLap DATE NOT NULL,
	GiaTriHienTai DECIMAL(32, 2) NOT NULL,
	MaTrangThai CHAR(36),
	NgayCapNhatCuoi DATE NOT NULL
	PRIMARY KEY (MaHopDong)
	FOREIGN KEY (MaYeuCau) REFERENCES tbYeuCauChoVay(MaYeuCau),
	FOREIGN KEY (MaNVTiepNhan) REFERENCES tbNhanVien(MaNV),
	FOREIGN KEY (MaTrangThai) REFERENCES tbTrangThaiHopDongVay(MaTrangThai)
)

CREATE TABLE tbTaiSanTheChap (
	MaTaiSan CHAR(36) NOT NULL,
	MaYeuCau CHAR(36) NOT NULL,
	MoTa NVARCHAR(512) NOT NULL,
	DinhGia DECIMAL(32, 2),
	MaTrangThai CHAR(36) NOT NULL
	PRIMARY KEY (MaTaiSan)
	FOREIGN KEY (MaTrangThai) REFERENCES tbTrangThaiTaiSan(MaTrangThai),
	FOREIGN KEY (MaYeuCau) REFERENCES tbYeuCauChoVay(MaYeuCau)
)

CREATE TABLE tbGiayToChungThuc (
	MaGiayToChungThuc CHAR(36) NOT NULL,
	MaTaiSan CHAR(36) NOT NULL
	PRIMARY KEY (MaGiayToChungThuc)
	FOREIGN KEY (MaTaiSan) REFERENCES tbTaiSanTheChap(MaTaiSan)
)

CREATE TABLE tbHoatDong (
	MaHoatDong CHAR(36) NOT NULL,
	MaNVThucHien CHAR(36) NOT NULL,
	ThoiDiemThucHien DATETIME NOT NULL,
	MoTa NVARCHAR(512) NOT NULL
	PRIMARY KEY (MaHoatDong)
	FOREIGN KEY (MaNVThucHien) REFERENCES tbNhanVien(MaNV)
)

CREATE TABLE tbHoatDongPhatTien (
	MaHoatDong CHAR(36) NOT NULL,
	MaHopDong CHAR(36) NOT NULL,
	MaNVThucHien CHAR(36) NOT NULL,
	ThoiDiemThucHien DATETIME NOT NULL,
	MaGiaoDich CHAR(36) NOT NULL
	PRIMARY KEY (MaHoatDong)
	FOREIGN KEY (MaHopDong) REFERENCES tbHopDongVay(MaHopDong),
	FOREIGN KEY (MaNVThucHien) REFERENCES tbNhanVien(MaNV),
	FOREIGN KEY (MaGiaoDich) REFERENCES tbGiaoDich(MaGiaoDich)
)

CREATE TABLE tbHoatDongThuTien (
	MaHoatDong CHAR(36) NOT NULL,
	MaHopDong CHAR(36) NOT NULL,
	MaKHThucHien CHAR(36) NOT NULL,
	MaNVThucHien CHAR(36) NOT NULL,
	ThoiDiemThucHien DATETIME NOT NULL,
	MaGiaoDich CHAR(36) NOT NULL
	PRIMARY KEY (MaHoatDong)
	FOREIGN KEY (MaHopDong) REFERENCES tbHopDongVay(MaHopDong),
	FOREIGN KEY (MaKHThucHien) REFERENCES tbKhachHang(MaKH),
	FOREIGN KEY (MaNVThucHien) REFERENCES tbNhanVien(MaNV),
	FOREIGN KEY (MaGiaoDich) REFERENCES tbGiaoDich(MaGiaoDich)
)

CREATE TABLE tbYeuCauChinhSuaHopDong (
	MaYeuCauChinhSua CHAR(36) NOT NULL,
	MaHopDong CHAR(36) NOT NULL,
	MaNVTiepNhan CHAR(36) NOT NULL,
	NgayTiepNhan DATE NOT NULL,
	MaKQXetDuyet CHAR(36),
	LyDo VARCHAR(512) NOT NULL
	PRIMARY KEY (MaYeuCauChinhSua) 
	FOREIGN KEY (MaHopDong) REFERENCES tbHopDongVay(MaHopDong),
	FOREIGN KEY (MaNVTiepNhan) REFERENCES tbNhanVien(MaNV),
	FOREIGN KEY (MaKQXetDuyet) REFERENCES tbKQXetDuyet(MaKQXetDuyet)
)

CREATE TABLE tbLoaiYeuCauChinhSua (
	MaLoaiYeuCau CHAR(36) NOT NULL,
	TenLoaiYeuCau NVARCHAR(128) NOT NULL,
	PRIMARY KEY (MaLoaiYeuCau)
)

CREATE TABLE tbChiTietYeuCauChinhSua (
	MaYeuCauChinhSua CHAR(36) NOT NULL,
	MaLoaiYeuCau CHAR(36) NOT NULL,
	GiaTriSoThuc DECIMAL(20, 10),
	GiaTriSoNguyen DECIMAL(20, 0)
	PRIMARY KEY (MaYeuCauChinhSua, MaLoaiYeuCau)
	FOREIGN KEY (MaYeuCauChinhSua) REFERENCES tbYeuCauChinhSuaHopDong(MaYeuCauChinhSua),
	FOREIGN KEY (MaLoaiYeuCau) REFERENCES tbLoaiYeuCauChinhSua(MaLoaiYeuCau)
)

CREATE TABLE tbThamSo (
	ThoiGianApDung DATETIME NOT NULL,
	VonVayCaNhanToiDa DECIMAL(32, 2) NOT NULL,
	VonVayToChucToiDa DECIMAL(32, 2) NOT NULL,
	YeuCauGiayToXacThuc BIT NOT NULL,
	TuoiDuocVayToiThieu INTEGER NOT NULL,
	KyHanToiDa INTEGER NOT NULL,
	KyHanToiThieu INTEGER NOT NULL,
	DinhGiaToiThieu DECIMAL(32, 2) NOT NULL,
	LaiSuatToiThieu DECIMAL(7, 3) NOT NULL,
	LaiSuatToiDa DECIMAL(7, 3) NOT NULL,
	ThoiGianThongBaoTraNo DECIMAL(5, 0) NOT NULL
	PRIMARY KEY (ThoiGianApDung)
)

CREATE TABLE tbBaoCaoDoiTuongVay (
	MaBaoCao CHAR(36) NOT NULL,
	MaKHBaoCao CHAR(36) NOT NULL,
	NgayBaoCao DATE NOT NULL,
	SuDungVonDungMucDich BIT NOT NULL,
	TaiSanTheChapDamBao BIT NOT NULL,
	DanhGia NVARCHAR(2048)
	PRIMARY KEY (MaBaoCao)
	FOREIGN KEY (MaKHBaoCao) REFERENCES tbKhachHang(MaKH)
)